INSERT INTO tb_client (name, created_At) VALUES ('Roberto', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('Ercules', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('Camila', NOW());

INSERT INTO tb_provider (name, created_At, tempo) VALUES ('Sony', NOW(), 30);
INSERT INTO tb_provider (name, created_At, tempo) VALUES ('Samsung', NOW(), 45);
INSERT INTO tb_provider (name, created_At, tempo) VALUES ('LG', NOW(), 15);
INSERT INTO tb_provider (name, created_At, tempo) VALUES ('Creative', NOW(), 10);
INSERT INTO tb_provider (name, created_At, tempo) VALUES ('Philco', NOW(), 60);
INSERT INTO tb_provider (name, created_At, tempo) VALUES ('Microsoft', NOW(), 5);

INSERT INTO tb_manufacturer (name, created_At) VALUES ('Sony2', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('Samsung2', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('LG2', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('Creative2', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('Philco2', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('Microsoft2', NOW());

INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'TELEVISÃO 60', 2, 2, 1, 13, NOW(), 1);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'TELEVISÃO 59', 2, 2, 1, 12, NOW(), 2);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'TELEVISÃO 58', 2, 2, 1, 11, NOW(), 3);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'TELEVISÃO 57', 2, 2, 1, 10, NOW(), 4);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'TELEVISÃO 56', 2, 2, 1, 9, NOW(), 5);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'TELEVISÃO 55', 2, 2, 1, 8, NOW(), 6);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'TELEVISÃO 54', 2, 2, 1, 7, NOW(), 6);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'TELEVISÃO 53', 2, 2, 1, 6, NOW(), 5);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'TELEVISÃO 52', 2, 2, 1, 5, NOW(), 4);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'TELEVISÃO 51', 2, 2, 1, 4, NOW(), 3);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'TELEVISÃO 50', 2, 2, 1, 3, NOW(), 2);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'TELEVISÃO 49', 2, 2, 1, 2, NOW(), 1);

INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-05-19','YYYY-MM-DD'), NOW(), 1	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-05-20','YYYY-MM-DD'), NOW(), 2	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-05-21','YYYY-MM-DD'), NOW(), 3	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-06-13','YYYY-MM-DD'), NOW(), 1	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-06-14','YYYY-MM-DD'), NOW(), 2	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-06-15','YYYY-MM-DD'), NOW(), 3	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-07-13','YYYY-MM-DD'), NOW(), 1	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-07-14','YYYY-MM-DD'), NOW(), 2	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-07-15','YYYY-MM-DD'), NOW(), 3	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-05-19','YYYY-MM-DD'), NOW(), 1	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-05-20','YYYY-MM-DD'), NOW(), 2	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-05-21','YYYY-MM-DD'), NOW(), 3	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-06-13','YYYY-MM-DD'), NOW(), 1	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-06-14','YYYY-MM-DD'), NOW(), 2	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-06-15','YYYY-MM-DD'), NOW(), 3	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-07-13','YYYY-MM-DD'), NOW(), 1	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-07-14','YYYY-MM-DD'), NOW(), 2	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-07-15','YYYY-MM-DD'), NOW(), 3	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-05-19','YYYY-MM-DD'), NOW(), 1	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-05-20','YYYY-MM-DD'), NOW(), 2	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-05-21','YYYY-MM-DD'), NOW(), 3	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-06-13','YYYY-MM-DD'), NOW(), 1	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-06-14','YYYY-MM-DD'), NOW(), 2	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-06-15','YYYY-MM-DD'), NOW(), 3	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-07-13','YYYY-MM-DD'), NOW(), 1	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-07-14','YYYY-MM-DD'), NOW(), 2	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-07-15','YYYY-MM-DD'), NOW(), 3	);

INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-05-19','YYYY-MM-DD'), NOW(), 6	);
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-05-20','YYYY-MM-DD'), NOW(), 5	);
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-05-21','YYYY-MM-DD'), NOW(), 4	);
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-06-13','YYYY-MM-DD'), NOW(), 6	);
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-06-14','YYYY-MM-DD'), NOW(), 5	);
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-06-15','YYYY-MM-DD'), NOW(), 4	);
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-07-13','YYYY-MM-DD'), NOW(), 6	);
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-07-14','YYYY-MM-DD'), NOW(), 5	);
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-07-15','YYYY-MM-DD'), NOW(), 4	);

INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (1,1,300);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (1,11,290);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (1,12,200);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (4,1,100);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (4,11,150);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (4,12,400);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (7,1,450);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (7,11,500);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (7,12,600);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (2,2,700);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (2,10,800);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (2,9,100);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (5,2,300);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (5,10,150);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (5,9,100);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (8,2,300);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (8,10,300);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (8,9,900);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (3,3,800);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (2,8,700);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (3,7,300);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (6,3,250);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (6,8,220);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (6,7,230);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (9,3,250);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (9,8,700);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (9,7,800);

INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (1,1,300);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (1,11,250);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (1,12,310);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (4,1,320);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (4,11,330);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (4,12,120);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (7,1,130);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (7,11,150);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (7,12,335);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (2,2,250);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (2,10,200);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (2,9,800);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (5,2,700);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (5,10,900);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (5,9,600);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (8,2,500);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (8,10,400);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (8,9,350);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (3,3,200);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (2,8,100);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (3,7,30);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (6,3,90);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (6,8,60);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (6,7,80);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (9,3,70);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (9,8,120);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (9,7,150);