INSERT INTO tb_client (name, created_At) VALUES ('MULTIFIX FIXACOES P/EMBALAGENS LTDA EPP', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('MARFIM-IND.E COM.FERRAMENTAS LTDA', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('BELGO BEKAERT ARAMES LTDA', NOW()); 
INSERT INTO tb_client (name, created_At) VALUES ('INDUSTRIA DE FORJADOS SAO ROMAO LTDA', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('STAM METALURGICA S.A', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('FABRICA DE TELAS E PENEIRAS SAO JORGE LTDA', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('LUX BRASIL INDUSTRIA E COMERCIO DE FIOS E CABOS LTDA', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('JOMARCA INDUSTRIAL DE PARAFUSOS LTDA', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('IV PLAST IND.E COM.LTDA', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('MORLAN S.A', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('ALIANCA METALURGICA S.A', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('CIA INDUSTRIAL H.CARLOS SCHNEIDER', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('O.V.D IMPORTADORA E DISTRIBUIDORA LTDA', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('REGINALDO ACIOLE BATISTA ME', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('ARCELOR MITTAL BRASIL S.A', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('GMB COMERCIO INDUSTRIA DE PROD.MET.LTDA', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('LUCIANO RODRIGO VECHIATTO', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('AZZO HIDRAULICOS DO BRASIL LTDA', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('METALURGICA LOTH LTDA', NOW());
INSERT INTO tb_client (name, created_At) VALUES ('MAJE DO NORDESTE IND E COM DE MAT ELETRICOS LTDA', NOW());


INSERT INTO tb_provider (name, created_At) VALUES ('BAUNGARTEN IND E COM LTDA', NOW());
INSERT INTO tb_provider (name, created_At) VALUES ('MEXICHEM BRASIL INDUSTRIA DE TRANSFORMACAO PLASTICA LTDA', NOW());
INSERT INTO tb_provider (name, created_At) VALUES ('PINCEIS ROMA LTDA - NORDESTE', NOW());
INSERT INTO tb_provider (name, created_At) VALUES ('ABB INDUSTRIAL CONNECTIONS AND SOLUTIONS PRODUTOS EQUIPAMENT', NOW());
INSERT INTO tb_provider (name, created_At) VALUES ('EDUARDO COMERCIO VAREJISTA EIRELE ME', NOW());
INSERT INTO tb_provider (name, created_At) VALUES ('ELETRO METALURGICA VENTI-DELTA LTDA', NOW());
INSERT INTO tb_provider (name, created_At) VALUES ('TECIDOS E ARMARINHO MIGUEL BARTOLOMEU S.A', NOW());
INSERT INTO tb_provider (name, created_At) VALUES ('SAINT GOBAIN DO BRASIL PRODUTOS INDUSTRIAIS E PARA CONSTRUCAO LTDA', NOW());
INSERT INTO tb_provider (name, created_At) VALUES ('VIQUA INDUSTRIA DE PLASTICOS LTDA', NOW());
INSERT INTO tb_provider (name, created_At) VALUES ('BLACK DECKER', NOW());
INSERT INTO tb_provider (name, created_At) VALUES ('FERTAK COMERCIO E IMPORTACAO LTDA', NOW());
INSERT INTO tb_provider (name, created_At) VALUES ('OPCAO CONDUTORES ELETRICOS EIRELI', NOW());
INSERT INTO tb_provider (name, created_At) VALUES ('NOVA DIRECAO TRANSPORTES LTDA', NOW());
INSERT INTO tb_provider (name, created_At) VALUES ('ANTONIO SERVICOS DE CONSTRUCOES', NOW());
INSERT INTO tb_provider (name, created_At) VALUES ('VALELUZ HIDRO ELETRICA VALENCIANA LTDA', NOW());
INSERT INTO tb_provider (name, created_At) VALUES ('SAO DOMINGOS EPI BOCAINA LTDA ME', NOW());
INSERT INTO tb_provider (name, created_At) VALUES ('BRASIL INTER COMEX ELETRONICOS E INFORMATICA EIRELI', NOW());
INSERT INTO tb_provider (name, created_At) VALUES ('CASA J NAKAO LTDA.', NOW());
INSERT INTO tb_provider (name, created_At) VALUES ('RODTEC EQUIPAMENTOS DE INFORMATICA EIRELI - ME', NOW());
INSERT INTO tb_provider (name, created_At) VALUES ('SILENIA BARRETO JADER', NOW());

INSERT INTO tb_manufacturer (name, created_At) VALUES ('ALIAN«A', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('P.FREE', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('SIL', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('S.ROM√O', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('MOMFORT', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('MAX', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('MINASUL', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('LAUFERR', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('FERTAK', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('THOMPSON', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('MORLAN', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('BELGO', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('JOMARCA', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('CARIOKINHA', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('IV PLAST', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('LOTH', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('MECTRONIC', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('NIHES', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('BESTFER', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('FERTAK', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('RAYCO', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('VALEPLAST', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('HERC', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('SG', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('PLASTUBOS', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('P.ROMA', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('HIDROFIX', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('MULTIFIX', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('AFIACO', NOW());
INSERT INTO tb_manufacturer (name, created_At) VALUES ('ARCELLOR', NOW());


INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'CABO FLEX.POWERFREE 1,50MM VERDE', 2, 2, 1, 13, NOW(), 1);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'CAVADEIRA LISA 1" AZUL', 2, 2, 1, 12, NOW(), 2);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'TORQUES ARMADOR VERDE 12" (30CM)', 2, 2, 1, 11, NOW(), 3);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'TALHADEIRA CHATA 10" (25CM)', 2, 2, 1, 10, NOW(), 4);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'PONTEIRA LISA 3/4"X8" (20CM)', 2, 2, 1, 30, NOW(), 5);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'DOBRADI«A P/PORTEIRA N 00', 2, 2, 1, 22, NOW(), 6);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'CADEADO STAM 45MM', 2, 2, 1, 7, NOW(), 6);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'PARAFUSO P/VASO N08 C/20', 2, 2, 1, 1, NOW(), 5);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'PREGO P/TELHA 18X30 C/50UND', 2, 2, 1, 15, NOW(), 4);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'PREGO A«O 12X12 COM CABE«A 1KG', 2, 2, 1, 20, NOW(), 3);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'ESCAPULA B10 (6,3X70) C/100UND', 2, 2, 1, 21, NOW(), 2);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'GANCHO B10 C/100UND', 2, 2, 1, 2, NOW(), 1);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'PARAFUSO MADEIRA 2,8X20 PHS CX/1000', 2, 2, 30, 13, NOW(), 1);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'PITAO B10 6,3 X 70 C/100UND', 2, 2, 1, 12, NOW(), 2);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'REBITE ALUM.J312 (3,2X12) CX1000', 2, 2, 1, 11, NOW(), 3);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'PREGO DE A«O ENCARTELADO 10X10 C/C 20GR', 2, 2, 1, 10, NOW(), 4);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'ARAME FIO 20 GALV. C/10M CX/10RLS', 2, 2, 1, 9, NOW(), 5);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'BUCHA IVPLAST B-5 C/1000 UND', 2, 2, 1, 8, NOW(), 6);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'CANTONEIRA MAO FRANCESA 20CM 6X8" BRANCA', 2, 2, 1, 7, NOW(), 6);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'FERROLHO 5" ZINCADO', 2, 2, 1, 6, NOW(), 5);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'TRINCO LOTH 2,0" GALV.ENCAR.', 2, 2, 1, 5, NOW(), 4);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'ESP¡TULA 10 CM CABO MADEIRA', 2, 2, 1, 4, NOW(), 3);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'INTERRUPTOR 1X PARALELO', 2, 2, 1, 3, NOW(), 2);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'PULSADOR P/CAMPAINHA C/PLACA', 2, 2, 1, 2, NOW(), 1);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'CONECTOR ANTENA C/PLACA 4X2', 2, 2, 1, 13, NOW(), 1);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'CAMPAINHA 127/220V BRANCA', 2, 2, 1, 12, NOW(), 2);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'TOMADA MECTRONIC 2P+T 10A C/PLACA', 2, 2, 1, 11, NOW(), 3);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'BALDE DE CHAPA 10L', 2, 2, 1, 10, NOW(), 4);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'LUVA DE LATEX G-8 AM C/FORRO CA 36066', 2, 2, 1, 30, NOW(), 5);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'CHAVE DE VIRAR FERRO 4 MEDIDAS', 2, 2, 1, 8, NOW(), 6);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'CAIXA SIFONADA 100X150X50', 2, 2, 1, 15, NOW(), 6);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'CAIXA P/ LINHA DE SOBREPOR 4X2 (115X75X40)', 2, 2, 1, 6, NOW(), 5);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'TELA SOLDADA MORLAN FIO 1,9MM 1.00MX25MT (5X10CM)', 2, 2, 1, 5, NOW(), 4);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'ESCOVA CEPA MADEIRA 177X55MM', 2, 2, 1, 13, NOW(), 1);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'ESCOVA DE A«O 3 FILEIRAS C/C PLAST', 2, 2, 1, 12, NOW(), 2);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'GARFO P/ROLO 23CM', 2, 2, 1, 11, NOW(), 3);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'BROXA PLAST.REDONDA 7,5CM', 2, 2, 1, 10, NOW(), 4);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'TELA HEX.MANG.(3") FIO16 50X0,80M', 2, 2, 1, 22, NOW(), 5);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'ESTICADOR ARAME LISO (CATRACA)', 2, 2, 1, 8, NOW(), 6);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'SENSOR', 2, 2, 1, 50, NOW(), 6);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'REDUCAO EXCENT.ESG. DN75X50', 2, 2, 1, 20, NOW(), 5);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'LUVA ESGOTO DN50', 2, 2, 1, 15, NOW(), 4);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'CURVA 90∫ ESGOTO LONGA DN100', 2, 2, 1, 10, NOW(), 3);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'DESEMPENADEIRA PLAST. 17X30CM C/ESPUMA ROMA/MAX', 2, 2, 1, 3, NOW(), 2);
INSERT INTO tb_product (codigo_Barras, referencia, descricao, unvenda, uncompra, quantidadecx, quantidade, created_At, manufacturer_id) VALUES (123456789, 987456321, 'VASSOURA MAX 18D ARAME FIXA C/C', 2, 2, 1, 6, NOW(), 1);


INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-04-01','YYYY-MM-DD'), NOW(), 1	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-04-20','YYYY-MM-DD'), NOW(), 2	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-04-10','YYYY-MM-DD'), NOW(), 3	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-06-13','YYYY-MM-DD'), NOW(), 4	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-06-14','YYYY-MM-DD'), NOW(), 5	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-06-15','YYYY-MM-DD'), NOW(), 6	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-07-13','YYYY-MM-DD'), NOW(), 7	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-07-14','YYYY-MM-DD'), NOW(), 8	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-09-15','YYYY-MM-DD'), NOW(), 9	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-05-19','YYYY-MM-DD'), NOW(), 1	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-05-01','YYYY-MM-DD'), NOW(), 2	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-05-21','YYYY-MM-DD'), NOW(), 3	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-06-03','YYYY-MM-DD'), NOW(), 4	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-03-14','YYYY-MM-DD'), NOW(), 5	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-03-15','YYYY-MM-DD'), NOW(), 6	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-07-13','YYYY-MM-DD'), NOW(), 7	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-07-07','YYYY-MM-DD'), NOW(), 8	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-07-15','YYYY-MM-DD'), NOW(), 9	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-01-19','YYYY-MM-DD'), NOW(), 1	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-02-20','YYYY-MM-DD'), NOW(), 2	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-05-21','YYYY-MM-DD'), NOW(), 3	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-01-13','YYYY-MM-DD'), NOW(), 4	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-06-24','YYYY-MM-DD'), NOW(), 5	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-06-25','YYYY-MM-DD'), NOW(), 6	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-09-13','YYYY-MM-DD'), NOW(), 7	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-09-14','YYYY-MM-DD'), NOW(), 8	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-09-15','YYYY-MM-DD'), NOW(), 9	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-02-19','YYYY-MM-DD'), NOW(), 1	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-02-20','YYYY-MM-DD'), NOW(), 2	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-02-21','YYYY-MM-DD'), NOW(), 3	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-06-13','YYYY-MM-DD'), NOW(), 4	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-06-14','YYYY-MM-DD'), NOW(), 5	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-06-15','YYYY-MM-DD'), NOW(), 6	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-07-13','YYYY-MM-DD'), NOW(), 7	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-07-14','YYYY-MM-DD'), NOW(), 8	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-07-15','YYYY-MM-DD'), NOW(), 9	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-02-21','YYYY-MM-DD'), NOW(), 3	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-04-26','YYYY-MM-DD'), NOW(), 4	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-04-25','YYYY-MM-DD'), NOW(), 5	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-06-15','YYYY-MM-DD'), NOW(), 6	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-08-13','YYYY-MM-DD'), NOW(), 7	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-08-14','YYYY-MM-DD'), NOW(), 8	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-07-15','YYYY-MM-DD'), NOW(), 9	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-10-19','YYYY-MM-DD'), NOW(), 1	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2020-10-20','YYYY-MM-DD'), NOW(), 2	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-05-19','YYYY-MM-DD'), NOW(), 19	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-09-19','YYYY-MM-DD'), NOW(), 20	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-08-20','YYYY-MM-DD'), NOW(), 11	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-05-21','YYYY-MM-DD'), NOW(), 12	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-06-13','YYYY-MM-DD'), NOW(), 13	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-11-14','YYYY-MM-DD'), NOW(), 14	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-06-15','YYYY-MM-DD'), NOW(), 15	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-05-21','YYYY-MM-DD'), NOW(), 12	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-06-13','YYYY-MM-DD'), NOW(), 13	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-07-14','YYYY-MM-DD'), NOW(), 14	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-06-15','YYYY-MM-DD'), NOW(), 15	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-07-13','YYYY-MM-DD'), NOW(), 16	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-07-14','YYYY-MM-DD'), NOW(), 17	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-07-15','YYYY-MM-DD'), NOW(), 18	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-10-13','YYYY-MM-DD'), NOW(), 16	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-09-14','YYYY-MM-DD'), NOW(), 17	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-08-15','YYYY-MM-DD'), NOW(), 18	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-05-20','YYYY-MM-DD'), NOW(), 11	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-05-21','YYYY-MM-DD'), NOW(), 12	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-04-13','YYYY-MM-DD'), NOW(), 1	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-04-14','YYYY-MM-DD'), NOW(), 14	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-04-15','YYYY-MM-DD'), NOW(), 15	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-04-13','YYYY-MM-DD'), NOW(), 16	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-07-14','YYYY-MM-DD'), NOW(), 17	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-05-19','YYYY-MM-DD'), NOW(), 10	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-11-20','YYYY-MM-DD'), NOW(), 11	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-11-21','YYYY-MM-DD'), NOW(), 2	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-12-13','YYYY-MM-DD'), NOW(), 3	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-12-14','YYYY-MM-DD'), NOW(), 4	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-12-15','YYYY-MM-DD'), NOW(), 5	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-10-13','YYYY-MM-DD'), NOW(), 6	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-11-14','YYYY-MM-DD'), NOW(), 7	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-12-15','YYYY-MM-DD'), NOW(), 8	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-03-15','YYYY-MM-DD'), NOW(), 18	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-05-20','YYYY-MM-DD'), NOW(), 11	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-05-19','YYYY-MM-DD'), NOW(), 10	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-04-20','YYYY-MM-DD'), NOW(), 11	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-05-21','YYYY-MM-DD'), NOW(), 12	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-06-13','YYYY-MM-DD'), NOW(), 13	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-02-14','YYYY-MM-DD'), NOW(), 14	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-02-15','YYYY-MM-DD'), NOW(), 15	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-07-13','YYYY-MM-DD'), NOW(), 16	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-07-14','YYYY-MM-DD'), NOW(), 17	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-07-15','YYYY-MM-DD'), NOW(), 18	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-05-19','YYYY-MM-DD'), NOW(), 10	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-05-20','YYYY-MM-DD'), NOW(), 1	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-02-21','YYYY-MM-DD'), NOW(), 12	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-06-13','YYYY-MM-DD'), NOW(), 13	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-06-14','YYYY-MM-DD'), NOW(), 14	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-06-15','YYYY-MM-DD'), NOW(), 15	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-07-13','YYYY-MM-DD'), NOW(), 20	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-01-14','YYYY-MM-DD'), NOW(), 2	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2019-12-15','YYYY-MM-DD'), NOW(), 18	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-05-19','YYYY-MM-DD'), NOW(), 8	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-08-20','YYYY-MM-DD'), NOW(), 9	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-11-21','YYYY-MM-DD'), NOW(), 1	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-11-13','YYYY-MM-DD'), NOW(), 2	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-03-14','YYYY-MM-DD'), NOW(), 3	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-03-15','YYYY-MM-DD'), NOW(), 4	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-07-13','YYYY-MM-DD'), NOW(), 5	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-07-14','YYYY-MM-DD'), NOW(), 6	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-07-15','YYYY-MM-DD'), NOW(), 7	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-07-19','YYYY-MM-DD'), NOW(), 19	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-01-13','YYYY-MM-DD'), NOW(), 20	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-12-19','YYYY-MM-DD'), NOW(), 19	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-12-30','YYYY-MM-DD'), NOW(), 16	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-12-19','YYYY-MM-DD'), NOW(), 19	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-12-20','YYYY-MM-DD'), NOW(), 17	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-12-21','YYYY-MM-DD'), NOW(), 1	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-12-13','YYYY-MM-DD'), NOW(), 2	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-12-14','YYYY-MM-DD'), NOW(), 13	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-12-15','YYYY-MM-DD'), NOW(), 4	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-12-13','YYYY-MM-DD'), NOW(), 5	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-12-14','YYYY-MM-DD'), NOW(), 6	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-11-15','YYYY-MM-DD'), NOW(), 7	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-10-19','YYYY-MM-DD'), NOW(), 19	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-10-20','YYYY-MM-DD'), NOW(), 20	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-10-19','YYYY-MM-DD'), NOW(), 19	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-10-20','YYYY-MM-DD'), NOW(), 20	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-10-21','YYYY-MM-DD'), NOW(), 1	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-10-13','YYYY-MM-DD'), NOW(), 12	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-09-14','YYYY-MM-DD'), NOW(), 3	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-09-15','YYYY-MM-DD'), NOW(), 4	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-09-13','YYYY-MM-DD'), NOW(), 19	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-09-14','YYYY-MM-DD'), NOW(), 6	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-08-15','YYYY-MM-DD'), NOW(), 7	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-08-13','YYYY-MM-DD'), NOW(), 11	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-07-19','YYYY-MM-DD'), NOW(), 19	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-07-30','YYYY-MM-DD'), NOW(), 20	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-07-19','YYYY-MM-DD'), NOW(), 19	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-06-20','YYYY-MM-DD'), NOW(), 10	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-06-21','YYYY-MM-DD'), NOW(), 1	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-06-13','YYYY-MM-DD'), NOW(), 2	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-05-14','YYYY-MM-DD'), NOW(), 3	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-05-15','YYYY-MM-DD'), NOW(), 4	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-05-13','YYYY-MM-DD'), NOW(), 5	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-05-14','YYYY-MM-DD'), NOW(), 16	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-04-15','YYYY-MM-DD'), NOW(), 7	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-04-19','YYYY-MM-DD'), NOW(), 19	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-04-20','YYYY-MM-DD'), NOW(), 20	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-03-19','YYYY-MM-DD'), NOW(), 15	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-03-20','YYYY-MM-DD'), NOW(), 20	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-03-21','YYYY-MM-DD'), NOW(), 1	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-02-13','YYYY-MM-DD'), NOW(), 2	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-02-14','YYYY-MM-DD'), NOW(), 3	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-02-15','YYYY-MM-DD'), NOW(), 4	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-01-13','YYYY-MM-DD'), NOW(), 5	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-01-14','YYYY-MM-DD'), NOW(), 6	);
INSERT INTO tb_exit (date, created_At, client_id ) VALUES (TO_TIMESTAMP('2018-01-15','YYYY-MM-DD'), NOW(), 7	);


INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-01-19','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-01-20','YYYY-MM-DD'), NOW(), 2	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-01-21','YYYY-MM-DD'), NOW(), 3	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-01-13','YYYY-MM-DD'), NOW(), 4	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-01-19','YYYY-MM-DD'), NOW(), 10 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-01-20','YYYY-MM-DD'), NOW(), 11 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-01-21','YYYY-MM-DD'), NOW(), 12 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-01-13','YYYY-MM-DD'), NOW(), 14 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-01-14','YYYY-MM-DD'), NOW(), 15 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-01-15','YYYY-MM-DD'), NOW(), 16 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-01-13','YYYY-MM-DD'), NOW(), 17 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-01-14','YYYY-MM-DD'), NOW(), 18 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-01-15','YYYY-MM-DD'), NOW(), 19 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-01-14','YYYY-MM-DD'), NOW(), 5	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-01-15','YYYY-MM-DD'), NOW(), 6	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-01-13','YYYY-MM-DD'), NOW(), 7	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-01-14','YYYY-MM-DD'), NOW(), 8	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-01-15','YYYY-MM-DD'), NOW(), 9	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-02-19','YYYY-MM-DD'), NOW(), 10 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-02-20','YYYY-MM-DD'), NOW(), 11 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-02-21','YYYY-MM-DD'), NOW(), 12 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-02-13','YYYY-MM-DD'), NOW(), 14 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-02-14','YYYY-MM-DD'), NOW(), 15 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-02-15','YYYY-MM-DD'), NOW(), 16 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-02-13','YYYY-MM-DD'), NOW(), 17 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-02-14','YYYY-MM-DD'), NOW(), 18 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-02-15','YYYY-MM-DD'), NOW(), 19 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-02-19','YYYY-MM-DD'), NOW(), 20 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-02-20','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-02-21','YYYY-MM-DD'), NOW(), 2	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-03-19','YYYY-MM-DD'), NOW(), 10 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-03-20','YYYY-MM-DD'), NOW(), 11 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-03-21','YYYY-MM-DD'), NOW(), 12 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-02-21','YYYY-MM-DD'), NOW(), 12 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-03-13','YYYY-MM-DD'), NOW(), 14 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-03-14','YYYY-MM-DD'), NOW(), 15 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-03-15','YYYY-MM-DD'), NOW(), 16 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-03-13','YYYY-MM-DD'), NOW(), 17 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-03-14','YYYY-MM-DD'), NOW(), 18 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-03-15','YYYY-MM-DD'), NOW(), 19 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-03-19','YYYY-MM-DD'), NOW(), 20 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-03-20','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-03-21','YYYY-MM-DD'), NOW(), 2	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-03-19','YYYY-MM-DD'), NOW(), 10 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-03-20','YYYY-MM-DD'), NOW(), 11 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-03-21','YYYY-MM-DD'), NOW(), 12 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-04-13','YYYY-MM-DD'), NOW(), 14 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-04-20','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-04-21','YYYY-MM-DD'), NOW(), 2	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-04-13','YYYY-MM-DD'), NOW(), 4	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-04-14','YYYY-MM-DD'), NOW(), 5	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-04-15','YYYY-MM-DD'), NOW(), 6	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-04-13','YYYY-MM-DD'), NOW(), 7	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-04-14','YYYY-MM-DD'), NOW(), 8	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-04-15','YYYY-MM-DD'), NOW(), 9	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-04-14','YYYY-MM-DD'), NOW(), 15 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-04-15','YYYY-MM-DD'), NOW(), 16 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-04-13','YYYY-MM-DD'), NOW(), 17 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-05-14','YYYY-MM-DD'), NOW(), 18 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-05-15','YYYY-MM-DD'), NOW(), 19 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-05-19','YYYY-MM-DD'), NOW(), 20 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-05-20','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-05-21','YYYY-MM-DD'), NOW(), 2	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-06-13','YYYY-MM-DD'), NOW(), 4	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-06-14','YYYY-MM-DD'), NOW(), 5	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-06-15','YYYY-MM-DD'), NOW(), 6	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-07-13','YYYY-MM-DD'), NOW(), 7	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-07-14','YYYY-MM-DD'), NOW(), 8	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-07-15','YYYY-MM-DD'), NOW(), 9	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-08-19','YYYY-MM-DD'), NOW(), 10 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-08-20','YYYY-MM-DD'), NOW(), 11 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-08-21','YYYY-MM-DD'), NOW(), 2	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-08-13','YYYY-MM-DD'), NOW(), 4	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-08-14','YYYY-MM-DD'), NOW(), 5	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-08-15','YYYY-MM-DD'), NOW(), 6	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-08-13','YYYY-MM-DD'), NOW(), 7	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-08-14','YYYY-MM-DD'), NOW(), 8	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-08-15','YYYY-MM-DD'), NOW(), 9	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-08-21','YYYY-MM-DD'), NOW(), 12 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-09-13','YYYY-MM-DD'), NOW(), 14 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-09-14','YYYY-MM-DD'), NOW(), 15 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-09-15','YYYY-MM-DD'), NOW(), 16 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-09-13','YYYY-MM-DD'), NOW(), 17 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-09-14','YYYY-MM-DD'), NOW(), 18 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-09-15','YYYY-MM-DD'), NOW(), 19 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-09-19','YYYY-MM-DD'), NOW(), 10 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-09-20','YYYY-MM-DD'), NOW(), 11 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-10-21','YYYY-MM-DD'), NOW(), 2	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-10-13','YYYY-MM-DD'), NOW(), 4	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-10-14','YYYY-MM-DD'), NOW(), 5	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-10-15','YYYY-MM-DD'), NOW(), 6	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-10-13','YYYY-MM-DD'), NOW(), 7	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-10-14','YYYY-MM-DD'), NOW(), 8	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-10-15','YYYY-MM-DD'), NOW(), 9	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-10-21','YYYY-MM-DD'), NOW(), 12 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-10-13','YYYY-MM-DD'), NOW(), 14 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-10-14','YYYY-MM-DD'), NOW(), 15 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-10-15','YYYY-MM-DD'), NOW(), 16 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-10-13','YYYY-MM-DD'), NOW(), 17 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-10-14','YYYY-MM-DD'), NOW(), 18 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-10-15','YYYY-MM-DD'), NOW(), 19 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-11-15','YYYY-MM-DD'), NOW(), 19 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-11-19','YYYY-MM-DD'), NOW(), 20 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-11-20','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-11-21','YYYY-MM-DD'), NOW(), 2	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-11-13','YYYY-MM-DD'), NOW(), 4	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-11-14','YYYY-MM-DD'), NOW(), 5	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-11-15','YYYY-MM-DD'), NOW(), 6	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-11-13','YYYY-MM-DD'), NOW(), 7	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-11-14','YYYY-MM-DD'), NOW(), 8	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-11-15','YYYY-MM-DD'), NOW(), 9	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-11-19','YYYY-MM-DD'), NOW(), 10 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-11-20','YYYY-MM-DD'), NOW(), 11 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-12-21','YYYY-MM-DD'), NOW(), 11 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-12-13','YYYY-MM-DD'), NOW(), 4  );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-12-14','YYYY-MM-DD'), NOW(), 5	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-12-15','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-12-13','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-12-14','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2018-12-15','YYYY-MM-DD'), NOW(), 9	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-01-19','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-01-20','YYYY-MM-DD'), NOW(), 2	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-01-21','YYYY-MM-DD'), NOW(), 3	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-01-13','YYYY-MM-DD'), NOW(), 4	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-01-19','YYYY-MM-DD'), NOW(), 10 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-01-20','YYYY-MM-DD'), NOW(), 11 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-01-21','YYYY-MM-DD'), NOW(), 12 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-01-13','YYYY-MM-DD'), NOW(), 14 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-01-14','YYYY-MM-DD'), NOW(), 15 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-01-15','YYYY-MM-DD'), NOW(), 16 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-01-13','YYYY-MM-DD'), NOW(), 17 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-01-14','YYYY-MM-DD'), NOW(), 18 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-01-15','YYYY-MM-DD'), NOW(), 19 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-01-14','YYYY-MM-DD'), NOW(), 5	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-01-15','YYYY-MM-DD'), NOW(), 6	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-01-13','YYYY-MM-DD'), NOW(), 7	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-01-14','YYYY-MM-DD'), NOW(), 8	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-01-15','YYYY-MM-DD'), NOW(), 9	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-02-19','YYYY-MM-DD'), NOW(), 10 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-02-20','YYYY-MM-DD'), NOW(), 11 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-02-21','YYYY-MM-DD'), NOW(), 12 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-02-13','YYYY-MM-DD'), NOW(), 14 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-02-14','YYYY-MM-DD'), NOW(), 15 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-02-15','YYYY-MM-DD'), NOW(), 16 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-02-13','YYYY-MM-DD'), NOW(), 17 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-02-14','YYYY-MM-DD'), NOW(), 18 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-02-15','YYYY-MM-DD'), NOW(), 19 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-02-19','YYYY-MM-DD'), NOW(), 20 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-02-20','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-02-21','YYYY-MM-DD'), NOW(), 2	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-03-19','YYYY-MM-DD'), NOW(), 10 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-03-20','YYYY-MM-DD'), NOW(), 11 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-03-21','YYYY-MM-DD'), NOW(), 12 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-02-21','YYYY-MM-DD'), NOW(), 12 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-03-13','YYYY-MM-DD'), NOW(), 14 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-03-14','YYYY-MM-DD'), NOW(), 15 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-03-15','YYYY-MM-DD'), NOW(), 16 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-03-13','YYYY-MM-DD'), NOW(), 17 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-03-14','YYYY-MM-DD'), NOW(), 18 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-03-15','YYYY-MM-DD'), NOW(), 19 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-03-19','YYYY-MM-DD'), NOW(), 20 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-03-20','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-03-21','YYYY-MM-DD'), NOW(), 2	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-03-19','YYYY-MM-DD'), NOW(), 10 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-03-20','YYYY-MM-DD'), NOW(), 11 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-03-21','YYYY-MM-DD'), NOW(), 12 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-04-13','YYYY-MM-DD'), NOW(), 14 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-04-20','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-04-21','YYYY-MM-DD'), NOW(), 2	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-04-13','YYYY-MM-DD'), NOW(), 4	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-04-14','YYYY-MM-DD'), NOW(), 5	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-04-15','YYYY-MM-DD'), NOW(), 6	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-04-13','YYYY-MM-DD'), NOW(), 7	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-04-14','YYYY-MM-DD'), NOW(), 8	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-04-15','YYYY-MM-DD'), NOW(), 9	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-04-14','YYYY-MM-DD'), NOW(), 15 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-04-15','YYYY-MM-DD'), NOW(), 16 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-04-13','YYYY-MM-DD'), NOW(), 17 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-05-14','YYYY-MM-DD'), NOW(), 18 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-05-15','YYYY-MM-DD'), NOW(), 19 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-05-19','YYYY-MM-DD'), NOW(), 20 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-05-20','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-05-21','YYYY-MM-DD'), NOW(), 2	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-06-13','YYYY-MM-DD'), NOW(), 4	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-06-14','YYYY-MM-DD'), NOW(), 5	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-06-15','YYYY-MM-DD'), NOW(), 6	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-07-13','YYYY-MM-DD'), NOW(), 7	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-07-14','YYYY-MM-DD'), NOW(), 8	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-07-15','YYYY-MM-DD'), NOW(), 9	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-08-19','YYYY-MM-DD'), NOW(), 10 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-08-20','YYYY-MM-DD'), NOW(), 11 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-08-21','YYYY-MM-DD'), NOW(), 2	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-08-13','YYYY-MM-DD'), NOW(), 4	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-08-14','YYYY-MM-DD'), NOW(), 5	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-08-15','YYYY-MM-DD'), NOW(), 6	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-08-13','YYYY-MM-DD'), NOW(), 7	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-08-14','YYYY-MM-DD'), NOW(), 8	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-08-15','YYYY-MM-DD'), NOW(), 9	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-08-21','YYYY-MM-DD'), NOW(), 12 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-09-13','YYYY-MM-DD'), NOW(), 14 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-09-14','YYYY-MM-DD'), NOW(), 15 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-09-15','YYYY-MM-DD'), NOW(), 16 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-09-13','YYYY-MM-DD'), NOW(), 17 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-09-14','YYYY-MM-DD'), NOW(), 18 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-09-15','YYYY-MM-DD'), NOW(), 19 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-09-19','YYYY-MM-DD'), NOW(), 10 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-09-20','YYYY-MM-DD'), NOW(), 11 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-10-21','YYYY-MM-DD'), NOW(), 2	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-10-13','YYYY-MM-DD'), NOW(), 4	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-10-14','YYYY-MM-DD'), NOW(), 5	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-10-15','YYYY-MM-DD'), NOW(), 6	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-10-13','YYYY-MM-DD'), NOW(), 7	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-10-14','YYYY-MM-DD'), NOW(), 8	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-10-15','YYYY-MM-DD'), NOW(), 9	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-10-21','YYYY-MM-DD'), NOW(), 12 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-10-13','YYYY-MM-DD'), NOW(), 14 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-10-14','YYYY-MM-DD'), NOW(), 15 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-10-15','YYYY-MM-DD'), NOW(), 16 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-10-13','YYYY-MM-DD'), NOW(), 17 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-10-14','YYYY-MM-DD'), NOW(), 18 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-10-15','YYYY-MM-DD'), NOW(), 19 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-11-15','YYYY-MM-DD'), NOW(), 19 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-11-19','YYYY-MM-DD'), NOW(), 20 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-11-20','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-11-21','YYYY-MM-DD'), NOW(), 2	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-11-13','YYYY-MM-DD'), NOW(), 4	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-11-14','YYYY-MM-DD'), NOW(), 5	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-11-15','YYYY-MM-DD'), NOW(), 6	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-11-13','YYYY-MM-DD'), NOW(), 7	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-11-14','YYYY-MM-DD'), NOW(), 8	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-11-15','YYYY-MM-DD'), NOW(), 9	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-11-19','YYYY-MM-DD'), NOW(), 10 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-11-20','YYYY-MM-DD'), NOW(), 11 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-12-21','YYYY-MM-DD'), NOW(), 11 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-12-13','YYYY-MM-DD'), NOW(), 4  );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-12-14','YYYY-MM-DD'), NOW(), 5	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-12-15','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-12-13','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-12-14','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2019-12-15','YYYY-MM-DD'), NOW(), 9	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-01-19','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-01-20','YYYY-MM-DD'), NOW(), 2	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-01-21','YYYY-MM-DD'), NOW(), 3	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-01-13','YYYY-MM-DD'), NOW(), 4	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-01-19','YYYY-MM-DD'), NOW(), 10 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-01-20','YYYY-MM-DD'), NOW(), 11 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-01-21','YYYY-MM-DD'), NOW(), 12 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-01-13','YYYY-MM-DD'), NOW(), 14 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-01-14','YYYY-MM-DD'), NOW(), 15 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-01-15','YYYY-MM-DD'), NOW(), 16 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-01-13','YYYY-MM-DD'), NOW(), 17 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-01-14','YYYY-MM-DD'), NOW(), 18 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-01-15','YYYY-MM-DD'), NOW(), 19 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-01-14','YYYY-MM-DD'), NOW(), 5	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-01-15','YYYY-MM-DD'), NOW(), 6	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-01-13','YYYY-MM-DD'), NOW(), 7	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-01-14','YYYY-MM-DD'), NOW(), 8	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-01-15','YYYY-MM-DD'), NOW(), 9	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-02-19','YYYY-MM-DD'), NOW(), 10 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-02-20','YYYY-MM-DD'), NOW(), 11 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-02-21','YYYY-MM-DD'), NOW(), 12 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-02-13','YYYY-MM-DD'), NOW(), 14 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-02-14','YYYY-MM-DD'), NOW(), 15 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-02-15','YYYY-MM-DD'), NOW(), 16 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-02-13','YYYY-MM-DD'), NOW(), 17 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-02-14','YYYY-MM-DD'), NOW(), 18 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-02-15','YYYY-MM-DD'), NOW(), 19 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-02-19','YYYY-MM-DD'), NOW(), 20 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-02-20','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-02-21','YYYY-MM-DD'), NOW(), 2	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-03-19','YYYY-MM-DD'), NOW(), 10 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-03-20','YYYY-MM-DD'), NOW(), 11 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-03-21','YYYY-MM-DD'), NOW(), 12 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-02-21','YYYY-MM-DD'), NOW(), 12 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-03-13','YYYY-MM-DD'), NOW(), 14 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-03-14','YYYY-MM-DD'), NOW(), 15 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-03-15','YYYY-MM-DD'), NOW(), 16 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-03-13','YYYY-MM-DD'), NOW(), 17 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-03-14','YYYY-MM-DD'), NOW(), 18 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-03-15','YYYY-MM-DD'), NOW(), 19 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-03-19','YYYY-MM-DD'), NOW(), 20 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-03-20','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-03-21','YYYY-MM-DD'), NOW(), 2	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-03-19','YYYY-MM-DD'), NOW(), 10 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-03-20','YYYY-MM-DD'), NOW(), 11 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-03-21','YYYY-MM-DD'), NOW(), 12 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-04-13','YYYY-MM-DD'), NOW(), 14 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-04-20','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-04-21','YYYY-MM-DD'), NOW(), 2	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-04-13','YYYY-MM-DD'), NOW(), 4	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-04-14','YYYY-MM-DD'), NOW(), 5	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-04-15','YYYY-MM-DD'), NOW(), 6	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-04-13','YYYY-MM-DD'), NOW(), 7	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-04-14','YYYY-MM-DD'), NOW(), 8	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-04-15','YYYY-MM-DD'), NOW(), 9	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-04-14','YYYY-MM-DD'), NOW(), 15 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-04-15','YYYY-MM-DD'), NOW(), 16 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-04-13','YYYY-MM-DD'), NOW(), 17 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-05-14','YYYY-MM-DD'), NOW(), 18 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-05-15','YYYY-MM-DD'), NOW(), 19 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-05-19','YYYY-MM-DD'), NOW(), 20 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-05-20','YYYY-MM-DD'), NOW(), 1	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-05-21','YYYY-MM-DD'), NOW(), 2	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-06-13','YYYY-MM-DD'), NOW(), 4	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-06-14','YYYY-MM-DD'), NOW(), 5	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-06-15','YYYY-MM-DD'), NOW(), 6	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-07-13','YYYY-MM-DD'), NOW(), 7	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-07-14','YYYY-MM-DD'), NOW(), 8	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-07-15','YYYY-MM-DD'), NOW(), 9	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-08-19','YYYY-MM-DD'), NOW(), 10 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-08-20','YYYY-MM-DD'), NOW(), 11 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-08-21','YYYY-MM-DD'), NOW(), 2	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-08-13','YYYY-MM-DD'), NOW(), 4	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-08-14','YYYY-MM-DD'), NOW(), 5	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-08-15','YYYY-MM-DD'), NOW(), 6	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-08-13','YYYY-MM-DD'), NOW(), 7	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-08-14','YYYY-MM-DD'), NOW(), 8	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-08-15','YYYY-MM-DD'), NOW(), 9	 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-08-21','YYYY-MM-DD'), NOW(), 12 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-09-13','YYYY-MM-DD'), NOW(), 14 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-09-14','YYYY-MM-DD'), NOW(), 15 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-09-15','YYYY-MM-DD'), NOW(), 16 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-09-13','YYYY-MM-DD'), NOW(), 17 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-09-14','YYYY-MM-DD'), NOW(), 18 );
INSERT INTO tb_input (date, created_At, provider_id ) VALUES (TO_TIMESTAMP('2020-09-15','YYYY-MM-DD'), NOW(), 19 );






INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (1,1,300);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (2,1,300);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (2,11,290);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (3,12,200);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (4,1,100);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (5,11,150);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (6,12,400);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (7,1,450);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (8,11,500);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (9,12,600);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (10,2,700);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (11,10,800);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (12,9,100);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (13,2,300);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (14,10,150);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (15,9,100);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (16,2,300);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (17,10,300);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (18,9,900);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (19,3,800);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (20,8,700);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (21,7,300);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (22,3,250);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (6,8,220);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (6,7,230);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (9,3,250);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (9,8,700);
INSERT INTO tb_inputproduct (input_id, product_id, qtd_itens) VALUES (9,7,800);

INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (1,1,300);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (1,11,250);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (1,12,310);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (4,1,320);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (4,11,330);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (4,12,120);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (7,1,130);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (7,11,150);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (7,12,335);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (2,2,250);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (2,10,200);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (2,9,800);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (5,2,700);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (5,10,900);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (5,9,600);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (8,2,500);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (8,10,400);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (8,9,350);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (3,3,200);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (2,8,100);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (3,7,30);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (6,3,90);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (6,8,60);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (6,7,80);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (9,3,70);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (9,8,120);
INSERT INTO tb_exitproduct (exit_id, product_id, qtd_itens) VALUES (9,7,150);


